Parameters:
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
Resources:
  WebAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our hosts and SSH from local only
      VpcId:
        Fn::ImportValue:        #returns the value of an output exported by another stack
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
  RoleForSSMAccess:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  ServerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles: 
        - !Ref RoleForSSMAccess 
  ServerInstance:
    Type: AWS::EC2::Instance
    Properties: 
      IamInstanceProfile: !Ref ServerInstanceProfile
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: 
            - !Ref WebAccessSecurityGroup
          SubnetId: 
            Fn::ImportValue: !Sub "${EnvironmentName}-PRIV-SN"
      ImageId: ami-05d72852800cbf29e
      InstanceType: t3.micro
      
Outputs:                #display the information specified by given ID  , considered as global variables we could say

    WebAccessSecurityGroup: 
        Description: A reference to the created WebAccessSecurityGroup
        Value: !Ref WebAccessSecurityGroup                            
        Export:
          Name: !Sub ${EnvironmentName}-WebAccessSecurityGroupID       #print UdacityProject-VPCID

    RoleForSSMAccess:
        Description: Public Routing
        Value: !Ref RoleForSSMAccess
        Export:
          Name: !Sub ${EnvironmentName}-RoleForSSMAccessID

    ServerInstanceProfile:
        Description: ServerInstanceProfile
        Value: !Ref ServerInstanceProfile
        Export:
          Name: !Sub ${EnvironmentName}-ServerInstanceProfileID
    
    ServerInstance:
        Description: ServerInstance
        Value: !Ref ServerInstance
        Export:
          Name: !Sub ${EnvironmentName}-ServerInstanceID


